### ISSUE TITLE
tomo3d and 45º angle..

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-tomo3d#21]
It flips dimensions when transformation matrix rotates the images more than 45 degrees. The reconstructed tomograms seems "cropped"

Reported by @fede-pe and @Vilax

**Comment by azazellochg** [comment]
if the abs(tilt axis angle) is in 45-135 range, the aligned stack is flipped (x/y are swapped) in imod, because the tilt axis must be vertical (along Y)

**Comment by Vilax** [comment]
I think this PR https://github.com/scipion-em/scipion-em-tomo3d/pulls fix this issue.
