### ISSUE TITLE
tomo3d: denoising crash when using bflow

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-em-tomo3d#24]
If B flow is selected as the denoising algorithm the program crashes with default and non-default parameters. it works as expected when denoising with EED.

![image](https://user-images.githubusercontent.com/49978869/203777110-15c30e0b-de36-43d4-aced-2cb1663f0927.png)

**Comment by JorMaister** [comment]
There's some permission denied message on the first line in the image. Could it be the reason?

**Comment by pconesa** [comment]
is tomobflow executable?

**Comment by fede-pe** [comment]
I don't know, I saw the permission error. This was in alter, as tomo user. That's why I found it strange. This is the software folder for tomo3d.
![image](https://user-images.githubusercontent.com/49978869/203841925-e7492d70-ed58-4d67-af91-fd05822cdcfb.png)

**Comment by pconesa** [comment]
Seems executable

**Comment by JorMaister** [comment]
Solved, tests using bflow are passing
